import { ConfigProviderProps } from 'ant-design-vue';

export default {
  autoInsertSpaceInButton: false,
  input: {
    autocomplete: 'off',
  },
  form: {
    autoComplete: 'off',
  },
  theme: {
    token: {
      colorPrimary: '#2871ff',
      colorSuccess: ' #59BF78',
      colorPrimaryHover: '#5991ff',
      colorPrimaryActive: '#2260d9',
      colorSuccessBg: '#EAF9F4',
      colorSuccessBorder: '#BDE5C9',
      colorSuccessBorderHover: '#8BD2A1',
      colorSuccessText: '#59BF78',
      colorSuccessHover: '#95de64',
      colorSuccessActive: '#52B06E',
      colorError: '#ff5633',
      colorErrorBg: '#FFD7CF',
      colorErrorBorder: '#FFBBAD',
      colorErrorBorderHover: '#FF8970',
      colorErrorActive: '#EB4F2F',
      colorWarning: '#FF9A2F',
      colorWarningBg: '#FFECD8',
      colorWarningBorder: '#FFD7AC',
      colorWarningBorderHover: '#FFB86D',
      colorWarningActive: '#EB8E2B',
      colorTextSecondary: '#242526',
      colorTextTertiary: '#606266',
      colorText: '#18191A',
      colorTextQuaternary: '#909398',
      colorBorder: '#D4D7D9',
      colorBorderSecondary: '#E1E3E5',
      fontFamily: '思源黑体',
    },
    components: {
      Table: {
        borderRadius: 6,
        borderRadiusLG: 8,
        colorLink: '#1677ff',
        padding: 16,
        paddingContentVerticalLG: 10,
        colorFillAlter: '#F2F3F4',
        controlItemBgActive: '#ebf1ff',
      },
      Button: {
        colorText: '#606266',
        colorLinkHover: '#5991FF',
        colorPrimaryHover: '#5991ff',
        colorPrimaryActive: '#2260D9',
        colorLinkActive: '#2260d9',
        colorTextDisabled: '#C1C4CB',
        colorBgContainerDisabled: '#F2F3F4',
        paddingContentHorizontal: 20,
        colorError: '#FF5633',
        colorErrorBorderHover: '#FF6F52',
        colorErrorActive: '#EB4F2F',
        controlHeight: 36,
        borderRadius: 4,
        marginXS: 4,
      },
      Input: {
        controlHeight: 36,
        paddingSM: 12,
        colorTextPlaceholder: '#C1C4CB',
        colorPrimaryHover: '#2871FF ',
        colorBgContainerDisabled: '#F2F3F4',
        colorTextDisabled: '#C1C4CB',
        colorBorder: '#D4D7D9',
        colorErrorBorderHover: '#FF5633',
        colorText: '#242526',
        borderRadius: 4,
      },
      InputNumber: {
        controlHeight: 36,
        colorText: '#18191A',
        colorTextPlaceholder: '#C1C4CB',
        colorPrimaryHover: '#2871FF',
        colorBgContainerDisabled: '#F2F3F4',
        colorTextDisabled: '#C1C4CB',
        colorError: '#FF5633',
        colorErrorBorderHover: '#FF5633',
        borderRadius: 4,
      },
      Radio: {
        colorText: '#606266',
        colorPrimaryHover: '#2871FF',
        colorBgContainerDisabled: '#F2F3F4',
        colorTextDisabled: '#C1C4CB',
        colorPrimaryActive: '#2871FF',
      },
      Checkbox: {
        colorText: '#606266',
        colorPrimaryHover: '#2871FF',
        colorBgContainerDisabled: '#F2F3F4',
        colorTextDisabled: '#C1C4CB',
        colorBorder: '#E1E3E5',
      },
      Select: {
        controlHeight: 36,
        fontSizeIcon: 12,
        colorText: '#242526',
        colorTextPlaceholder: '#C1C4CB',
        colorPrimaryHover: '#2871FF',
        colorFillSecondary: 'rgba(0, 0, 0, 0.06)',
        colorBgContainerDisabled: '#F2F3F4',
        colorTextDisabled: '#C1C4CB',
        colorErrorOutline: 'rgba(255, 38, 5, 0.06)',
        colorErrorHover: '#FF5633 ',
        borderRadius: 4,
      },
      Switch: {
        // controlHeight: 22,
        colorTextTertiary: '#606266',
        opacityLoading: 0.3,
      },
      Cascader: {
        controlHeight: 34,
        colorPrimaryHover: '#2871FF ',
        colorBgContainerDisabled: '#F2F3F4',
        colorTextDisabled: '#C1C4CB',
      },
      DatePicker: {
        controlHeight: 36,
        colorText: '#242526',
        colorTextPlaceholder: '#C1C4CB',
        colorPrimaryHover: '#2871FF',
        colorPrimaryBorder: '#2871FF',
        colorLinkHover: '#69b1ff',
        colorBgContainerDisabled: '#F2F3F4',
        colorTextDisabled: '#C1C4CB',
        borderRadius: 4,
      },
      TreeSelect: {
        controlHeightSM: 34,
        colorText: '#242526',
        colorTextDisabled: '#C1C4CB',
        colorBgContainerDisabled: '#F2F3F4',
      },
      Upload: {
        marginXS: 4,
        fontSize: 12,
        colorPrimaryHover: '#2871ff',
      },
      Pagination: {
        controlHeight: 30,
        colorBgContainerDisabled: '#F2F3F4',
        colorText: '#242526',
        colorTextPlaceholder: '#C1C4CB ',
        borderRadius: 2,
      },
      Tabs: {
        margin: 16,
        colorPrimaryHover: '#5991FF',
        colorText: '#606266',
        borderRadiusLG: 4,
        padding: 16,
        colorBgContainer: 'rgba(245, 247, 250, 1)',
        colorFillAlter: 'rgba(0, 0, 0, 0)',
      },
      Modal: {
        colorText: '#242526 ',
        borderRadiusLG: 4,
      },
      Tree: {
        lineHeight: 1.5714285714285716,
        controlHeightSM: 34,
        controlInteractiveSize: 16,
        colorText: '#606266',
        paddingXS: 4,
        controlItemBgHover: 'rgba(0, 0, 0, 0.0)',
        controlItemBgActive: 'rgba(0, 0, 0, 0.0)',
      },
      Dropdown: {
        controlItemBgHover: '#F5F5F5',
        controlHeight: 34,
      },
      Form: {
        marginLG: 20,
      },
      Menu: {
        colorItemBg: '#103566',
        colorSubItemBg: '#0D2F59',
        colorItemText: '#ffffff',
        colorItemBgHover: '#0d3e80',
        radiusItem: 4,
      },
    },
  },
} as ConfigProviderProps;
